"""Database module for social-hook."""

from social_hook.db.connection import get_connection, init_database
from social_hook.db.operations import (
    get_active_arcs,
    get_all_pending_drafts,
    get_all_projects,
    get_arc_posts,
    get_draft,
    get_draft_changes,
    get_draft_tweets,
    get_lifecycle,
    get_milestone_summaries,
    get_narrative_debt,
    get_pending_drafts,
    get_project,
    get_project_summary,
    get_recent_decisions,
    get_recent_posts,
    get_recent_posts_for_context,
    get_schema_version,
    get_summary_freshness,
    get_usage_summary,
    increment_narrative_debt,
    insert_arc,
    insert_decision,
    insert_draft,
    insert_draft_change,
    insert_draft_tweet,
    insert_lifecycle,
    insert_milestone_summary,
    insert_narrative_debt,
    insert_post,
    insert_project,
    insert_usage,
    reset_narrative_debt,
    supersede_draft,
    update_arc,
    update_draft,
    update_lifecycle,
    update_project_summary,
)
from social_hook.db.schema import SCHEMA_VERSION, apply_migrations, create_schema

__all__ = [
    # Connection
    "get_connection",
    "init_database",
    # Schema
    "create_schema",
    "apply_migrations",
    "SCHEMA_VERSION",
    # Operations
    "get_schema_version",
    "insert_project",
    "get_project",
    "get_all_projects",
    "insert_decision",
    "get_recent_decisions",
    "insert_draft",
    "get_draft",
    "update_draft",
    "supersede_draft",
    "get_pending_drafts",
    "get_all_pending_drafts",
    "insert_draft_tweet",
    "get_draft_tweets",
    "insert_draft_change",
    "get_draft_changes",
    "insert_post",
    "get_recent_posts",
    "get_recent_posts_for_context",
    "insert_lifecycle",
    "get_lifecycle",
    "update_lifecycle",
    "insert_arc",
    "update_arc",
    "get_active_arcs",
    "get_arc_posts",
    "insert_narrative_debt",
    "get_narrative_debt",
    "increment_narrative_debt",
    "reset_narrative_debt",
    "insert_usage",
    "get_usage_summary",
    # Project Summary
    "update_project_summary",
    "get_project_summary",
    "get_summary_freshness",
    # Milestone Summaries
    "insert_milestone_summary",
    "get_milestone_summaries",
]
